services:
  - type: web
    name: stock-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --worker-class gthread --worker-tmp-dir /dev/shm --log-level info --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 100 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONUNBUFFERED
        value: 1
      - key: WEB_CONCURRENCY
        value: 1
